CREATE TABLE IF NOT EXISTS notes (
  id INT AUTO_INCREMENT,
  title VARCHAR(255),
  content VARCHAR(255) NOT NULL,
  date_created DATE DEFAULT CURRENT_DATE ON UPDATE CURRENT_DATE,
  PRIMARY KEY (id)
);